### PR TITLE
Add setup.py and update doctests to run on Python2.7 and 3.x

### PR DESCRIPTION
**Pull request by pombredanne**
For your consideration:
* Move boolean.py to a proper package with an __init__ 
* Add revised BSD license text and updated notices, for you to review for accuracy
* Create setup.py and config for tests and wheels. Use `python setup.py test` for testing
* Updated README, doc and doctests for Python 2 and 3.

### CODE REVIEW

**Comment by pombredanne** [comment]
@bastikr @Kronuz following the discussions on https://github.com/bastikr/boolean.py/pull/7 I will provide updated patches. Now one important thing to decide is the code structure: we have a `boolean` top dir which is not a proper package. I made that a package by renaming `boolean/boolean.py` to `boolean/__init__.py` but this is a source of problems: this rename creates a "wall" in the history.
So I suggest instead to do no renaming at all and consider the `boolean` top dir as if it were a `src` dir in a more conventional layout. And I will deal with the package injection in the setup.py proper.

**Comment by bastikr** [comment]
Isn't renaming automatically supported by git? Even if not I think it would be better to use the proper layout. However, I think it is cleaner to not put too much code into the __init__.py but keep a separate boolean/boolean.py file and just make the necessary functions available in __init__.py

**Comment by pombredanne** [comment]
@bastikr yes renaming is supported within reason.

**Comment by pombredanne** [comment]
@bastikr this is rebased now.

**Comment by bastikr** [comment]
This looks great - thank you! Merged.

**Pull request merged**
