### PR TITLE
Python 2 compatibility

### PR DESCRIPTION
**Pull request by Kronuz**
I added Python 2 compatibility and PEP 8 conformance in this pull request

### CODE REVIEW

**Comment by bastikr** [comment]
Sorry, I really don't like the changes that are necessary for python2 compatibility. The problem is that changing a function from f(*, eval=True) to f(*args, **kwargs) is not identical and allows to call the second function with an arbitrary amount of positional and keyword arguments. Of course it would be possible to explicitly check that args and kwargs are empty besides an optional keyword "eval" but it makes the code uglier. Also in the current state one can see immediately what keywords are allowed from just looking at the function declaration, in the proposed new way one would have to read through the whole function definition for a hint of which arguments are allowed.
I don't know what the best way to proceed is at this point. Maybe adding a separate python2 compatible file would be okay, although then there is the problem of keeping two separate files up to date.

The PEP 8 conformance is a good idea btw., I didn't commit it yet since the changes are on top of the python2 compatibility changes.

Thank you for your work and I hope we can find a solution that makes both of us happy!

**Comment by Kronuz** [comment]
Yes, it's a bad thing Python 2 lacks that expressiveness for the parameters. I currently *need* Python 2, thus the changes, but it's understandable, no one likes passing generic `*args, **kwargs`.

I also changed other things in my local fork as I'm not sure why/how I should use some functionality.

First, `bool(TRUE)` could also be (and currently) is True, but `bool(FALSE)` should, I think, also be False, but it isn't. I added `__bool__()` (and `__nozero__()` for Python 2) to TRUE and FALSE classes.

Secondly, I added `&`, `|` and `!` as alternatives for parsing Boolean expressions and `__and__()` and `__or__()` to `Expression` (I print the strings something as `"a&(b|c)"` instead of `"a*(b+c)"` as our developers are more familiar with the "&" and "|" notation, but supporting both doesn't hurt.

Thirdly, I also extended the parser so it takes symbols that contain underscores and dots. What characters make a symbol could/should be made configurable by the user instead, perhaps by using a regexp of allowed symbol names.

Finally, I'm using the Boolean expressions to pass Boolean rules and parsing them (and simplifying them) and then, how do I tell the expression to use certain symbols as True or False to give me end result of the evaluated symbols?

I currently added some changes to `eval()` to be able to pass a mapping of symbols to TRUE/FALSE during the evaluation. `eval()` received `**evalkwargs`,  which I guessed it was for the purpose of passing that mapping of symbols, as it only seemed intuitive it would, but it didn't do anything with them. Also, once expressions are flagged as canonical, `eval()` a second time doesn't do anything. So I changed `eval()` to save the dictionary object in `**evalkwargs` in a variable so next time I call `eval()` it returns immediately only if the saved `evalkwargs` is equal to the passed one (thus it's already been processed under that `evalkwargs` context as canonical) and I also use the passed `evalkwargs` in the Symbol's `eval()` as the symbol mapping to look for the value of symbol, so it returns either TRUE or FALSE, if it's there, or the symbol itself (`self`), if it's not.

**Comment by pombredanne** [comment]
Guys, I am a moron: I just pushed essentially similar fixes minus pep8 plus setup.py in this https://github.com/bastikr/boolean.py/pull/8
@Kronuz I also need py2 support and likely a Quine-McCluskey expression minimization
@bastikr if you do not want to support python2, then @Kronuz and I could maintain a fork separately and push to pypi :)

**Comment by pombredanne** [comment]
I should have checked PRs before ;)

**Comment by bastikr** [comment]
Oh wow. I completely missed @Kronuz last post which makes some reasonable changes. And thank you @pombredanne, your fixes seem like a real improvement! I still think that using the python2 function signature syntax is much uglier but python2 support seems to be more important. Maintaining two different versions is in my opinion not worth the additional effort, so let's just change it. However, I'm pretty sure that the patch provided by @Kronuz will at least partly conflict with your changes. If you want to I can add you as collaborator and give you push access to the repository and maybe you have time to extract the additional fixes from @Kronuz.

**Comment by Kronuz** [comment]
Hey, what about the other changes I mentioned above? Should I be making another pull request for those? Are those changes in anyway something that seem worth to have/add to boolean.py?

**Comment by pombredanne** [comment]
IMHO @bastikr you can pull in @Kronuz changes in this PR. Core code changes are better than mine in every respect. I will re-base mine on top and re-push them. I am fine to be a collaborator too.

@Kronuz Your suggestions make a lot of sense to me. They would be best in a separate PRs though.

**Comment by bastikr** [comment]
I agree that the suggestions make sense but lets talk about them in a separate thread - @Kronuz can you open a new issues for each of your proposals? Maybe one for the parser improvement and another for your changes in eval?

Okay lets first focus on the python 2.7 compatibility. You both get rid of the f(x, *, eval=True) syntax by replacing it by f(x, *args, **kwargs). I would honestly prefer the approach of just removing the * from the signature wherever this is possible, i.e. f(x, eval=True). Is there maybe some point I'm missing? I tried it out in the python2.7 branch (https://github.com/bastikr/boolean.py/tree/python2.7) and it seems to work.

The PEP changes are great and should definitely be used.

**Comment by pombredanne** [comment]
@bastikr I assumed that you needed variadic args... But if you do not need them, then things are much simpler. The code in your 2.7 branch just looks a-ok to me.

**Comment by bastikr** [comment]
Great if @Kronuz has no objections I will tomorrow merge his PEP8 patch and then we can move on to your changes @pombredanne.

**Comment by bastikr** [comment]
I rebased the PEP8 commit onto the python2.7 branch. I think we can close this pull request now and continue with @pombredanne's pull request.

**Comment by pombredanne** [comment]
@Kronuz  you said:
> I also changed other things in my local fork as I'm not sure why/how I should use some functionality.

Is this something you could push in a branch of your public fork so we can look at it?

**Comment by Kronuz** [comment]
Absolutely, I will make some pull requests based on current master for each of my proposed changes.

**Comment by pombredanne** [comment]
@Kronuz excellent.... I created the tickets for your items FWIW
@bastikr your wrote "I think we can close"... go for it!

**Pull request closed without merging**
