### PR TITLE
Allow custom Symbol class

### PR DESCRIPTION
**Pull request by Kronuz**
Allow swapping the Symbol class used during parsing. Also, Symbol knows what characters it takes (for me I needed dot, colons and slashes as part of the symbols, so that's what the default Symbol takes too now). This addresses something it was mentioned in issue #9 by @pombredanne.

### CODE REVIEW

**Comment by pombredanne** [comment]
I wonder if this could be made simpler altogether, possibly by accepting a tokenized list as an input.
This list could contain either strings of Symbol objects for symbols, and the tokenization could be something that could be arbitrarily complex if needed. But it might not mean invalidate this patch anyway.

**Comment by bastikr** [comment]
I don't think that we should put any of the code related to parsing into the symbol class. There is no reason why it shouldn't accept any string, at the moment it even allows any kind of object. We should this logic only into the parse function. Something like

    parse(expr, eval=True, isinitialsymbolchar=str.isalpha, issymbolchar=str.isalnum)

would work but maybe there are better ways.

**Comment by Kronuz** [comment]
@pombredanne, accepting tokenized input would imply the tokenizer knows how to tokenize something that cannot possibly get much more complex than just deciding what is a symbol and what not; boolean algebra parsing is simple. I'd agree with @bastikr in that probably we shouldn't mix parsing with `Symbol`; however, maybe passing a single function as a parameter that receives the current character and perhaps the current position of such character as part of the symbol string would suffice. Something like:

```python
def ischar(char, pos):
    if pos == 0:
        return char.isalpha()
    else:
        return char.isalnum()

...

def parse(expr, eval=True, ischar=ischar):
    ...
```

**Comment by bastikr** [comment]
Yeah, this way is cleaner than my approach. Maybe rename ischar  to issymbolchar to make it completely clear for what it is used?

**Comment by Kronuz** [comment]
@bastikr, modified pull request so it fit your suggestions

**Comment by pombredanne** [comment]
IMHO using the standard library `tokenize` module would be much simpler.

**Comment by Kronuz** [comment]
I suppose we could first use this patch (just so it's in the history, maybe) and then apply the proposed tokenizer after some testing...

**Comment by bastikr** [comment]
Yes this works for me. @pombredanne do you agree? If so please merge it.

**Comment by pombredanne** [comment]
@bastikr This conflicts with #23 ... So lets review #23 to decide which is the better approach

**Comment by pombredanne** [comment]
@Kronuz note that I am entirely fine to merge first and then rebase on top. But ATM this branch is stale and will need a manual merge too.

**Comment by Kronuz** [comment]
I've rebased this one. It can now be merged

**Comment by bastikr** [comment]
Ok it seems we agree to merge this first and then swap it with the new tokenizer afterwards. I'll merge it!

**Pull request merged**
